version: '3.2'

services:
  redis:
    image: redis:alpine
    restart: always
  web:
    build:
      context: ./project
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: always
