"""empty message

Revision ID: 4f2a817cfbce
Revises: 
Create Date: 2021-09-09 09:24:58.888404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2a817cfbce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('reportId', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('attackId', sa.Integer(), nullable=True),
    sa.Column('log', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['attackId'], ['attack.attackId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reportId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###
