"""empty message

Revision ID: df0f70e18b36
Revises: 4f2a817cfbce
Create Date: 2021-09-09 11:48:07.129620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0f70e18b36'
down_revision = '4f2a817cfbce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('startTime', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'startTime')
    # ### end Alembic commands ###
